version: 2.1

orbs:
  maven: circleci/maven@0.0.12

jobs:
  build:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run: mvn package
  deploy:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run: mvn deploy
  release:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run: ./mvnw release:prepare
      - run: ./mvnw release:perform

workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - deploy:
          requires:
            - test
